[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = "Programming Language :: Python :: 3.10, License :: Aladdin Free Public License (AFPL)"
authors = ["IvanPyGit <93933140+IvanPyGit@users.noreply.github.com>"]
packages = [
  { include = "brain_games" },
]
repository = "https://github.com/IvanPyGit/python-project-lvl1"

[tool.poetry.dependencies]
python = "^3.8,<4.0"
prompt = "^0.4.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
brain-even = "brain_games.scripts.brain_even:main"
brain-calc = "brain_games.scripts.brain_calc:main"
brain-gcd = "brain_games.scripts.brain_gcd:main"
brain-progression = "brain_games.scripts.brain_progression:main"
brain-prime = "brain_games.scripts.brain_prime:main"